### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by sidsalve** [sidsalve/learning_python_examples#1]
run program **fibonacci.py** and enter the characters, don't enter a number

**Comment by sidsalve** [comment]
how to reproduce?
run file --> python fibonacci.py
here don't enter a number, enter the character 
you will see an issue

**Comment by Param-g** [comment]
This program is only for creating fibonacci series up to entered number only that's why i am only accepting the integer value from user. Using num = int(input("Enter a number")).

**Comment by sidsalve** [comment]
please apply simple validation and exception handling as well, handling exception is a sign of good developer.
